{% set name = "brainglobe-space" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainglobe_space-{{ version }}.tar.gz
  sha256: a20f576d0a264dc2e15bf99d1b6a4a0f11198776edaecd247e27a185827d6a79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy

test:
  imports:
    - brainglobe_space
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brainglobe/brainglobe-space
  summary: Anatomical space conventions made easy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - willGraham01
    - alessandrofelder
    - adamltyson
